### ISSUE TITLE
qcow2 image output

### ISSUE THREAD

**Issue by cbluth** [ottomatica/slim#31]
Can slim produce qcow2 images?

**Comment by chrisparnin** [comment]
It currently does not, but it should be possible to plug-in to a utility like `qemu-img`.

**Comment by chrisparnin** [comment]
@cbluth We're in the process of addressing this with some code that will allow providing format preference when a provider might have multiple options: `slim build --format=qcow2`.

**Comment by gjabell** [comment]
@cbluth We just merged a patch that allows building qcow2 (#37), which allows you to specify a format flag (`-f`) to build additional formats. In your case, `slim build [image] -p kvm -f qcow2` will add a `slim.qcow2` to the image's registry entry (`$HOME/.slim/registry/[image]`). Note that `qcow2` is currently only available when building for the KVM provider, since it requires `qemu-img` to convert.

Let us know if you run into any issues!

**Comment by cbluth** [comment]
i will check it out!

**Comment by chrisparnin** [comment]
Closing issue since we now support qcow2 output. Can revisit any problems with new issue. Thanks!
